<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $karyawan = [
            // Direktur
            [
                'id' => Str::uuid(),
                'nip' => 'DIR001',
                'rfid_card_number' => 'CARD000001',
                'nama' => 'Budi Santoso',
                'email' => 'budi.santoso@company.com',
                'jabatan' => 'Direktur Utama',
                'departemen' => 'Direksi',
                'telepon' => '081234567001',
                'alamat' => 'Jl. Sudirman No. 1, Jakarta Pusat',
                'tanggal_masuk' => '2010-01-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 25000000.00,
                'tunjangan_jabatan' => 15000000.00,
                'tunjangan_transport' => 3000000.00,
                'tunjangan_makan' => 2000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Managers
            [
                'id' => Str::uuid(),
                'nip' => 'MGR001',
                'rfid_card_number' => 'CARD000002',
                'nama' => 'Siti Nurhaliza',
                'email' => 'siti.nurhaliza@company.com',
                'jabatan' => 'Manager HR',
                'departemen' => 'Human Resources',
                'telepon' => '081234567002',
                'alamat' => 'Jl. Gatot Subroto No. 15, Jakarta Selatan',
                'tanggal_masuk' => '2012-03-20',
                'status' => 'AKTIF',
                'gaji_pokok' => 15000000.00,
                'tunjangan_jabatan' => 7000000.00,
                'tunjangan_transport' => 2000000.00,
                'tunjangan_makan' => 1500000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'MGR002',
                'rfid_card_number' => 'CARD000003',
                'nama' => 'Ahmad Dahlan',
                'email' => 'ahmad.dahlan@company.com',
                'jabatan' => 'Manager IT',
                'departemen' => 'Information Technology',
                'telepon' => '081234567003',
                'alamat' => 'Jl. Rasuna Said No. 25, Jakarta Selatan',
                'tanggal_masuk' => '2013-05-10',
                'status' => 'AKTIF',
                'gaji_pokok' => 16000000.00,
                'tunjangan_jabatan' => 7500000.00,
                'tunjangan_transport' => 2000000.00,
                'tunjangan_makan' => 1500000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'MGR003',
                'rfid_card_number' => 'CARD000004',
                'nama' => 'Rina Wulandari',
                'email' => 'rina.wulandari@company.com',
                'jabatan' => 'Manager Finance',
                'departemen' => 'Finance',
                'telepon' => '081234567004',
                'alamat' => 'Jl. Thamrin No. 30, Jakarta Pusat',
                'tanggal_masuk' => '2014-07-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 15500000.00,
                'tunjangan_jabatan' => 7200000.00,
                'tunjangan_transport' => 2000000.00,
                'tunjangan_makan' => 1500000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Senior Staff
            [
                'id' => Str::uuid(),
                'nip' => 'SNR001',
                'rfid_card_number' => 'CARD000005',
                'nama' => 'Andi Wijaya',
                'email' => 'andi.wijaya@company.com',
                'jabatan' => 'Senior Software Engineer',
                'departemen' => 'Information Technology',
                'telepon' => '081234567005',
                'alamat' => 'Jl. Kuningan No. 12, Jakarta Selatan',
                'tanggal_masuk' => '2015-02-01',
                'status' => 'AKTIF',
                'gaji_pokok' => 12000000.00,
                'tunjangan_jabatan' => 4000000.00,
                'tunjangan_transport' => 1500000.00,
                'tunjangan_makan' => 1000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'SNR002',
                'rfid_card_number' => 'CARD000006',
                'nama' => 'Dewi Lestari',
                'email' => 'dewi.lestari@company.com',
                'jabatan' => 'Senior Accountant',
                'departemen' => 'Finance',
                'telepon' => '081234567006',
                'alamat' => 'Jl. Kemang Raya No. 45, Jakarta Selatan',
                'tanggal_masuk' => '2015-06-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 11000000.00,
                'tunjangan_jabatan' => 3500000.00,
                'tunjangan_transport' => 1500000.00,
                'tunjangan_makan' => 1000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Junior Staff
            [
                'id' => Str::uuid(),
                'nip' => 'JNR001',
                'rfid_card_number' => 'CARD000007',
                'nama' => 'Rudi Hartono',
                'email' => 'rudi.hartono@company.com',
                'jabatan' => 'Software Engineer',
                'departemen' => 'Information Technology',
                'telepon' => '081234567007',
                'alamat' => 'Jl. Menteng No. 8, Jakarta Pusat',
                'tanggal_masuk' => '2018-03-10',
                'status' => 'AKTIF',
                'gaji_pokok' => 8000000.00,
                'tunjangan_jabatan' => 2000000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR002',
                'rfid_card_number' => 'CARD000008',
                'nama' => 'Maya Sari',
                'email' => 'maya.sari@company.com',
                'jabatan' => 'HR Staff',
                'departemen' => 'Human Resources',
                'telepon' => '081234567008',
                'alamat' => 'Jl. Cikini Raya No. 22, Jakarta Pusat',
                'tanggal_masuk' => '2019-01-20',
                'status' => 'AKTIF',
                'gaji_pokok' => 7000000.00,
                'tunjangan_jabatan' => 1500000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR003',
                'rfid_card_number' => 'CARD000009',
                'nama' => 'Bambang Susilo',
                'email' => 'bambang.susilo@company.com',
                'jabatan' => 'Accountant',
                'departemen' => 'Finance',
                'telepon' => '081234567009',
                'alamat' => 'Jl. Tebet Barat No. 18, Jakarta Selatan',
                'tanggal_masuk' => '2019-05-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 7500000.00,
                'tunjangan_jabatan' => 1800000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR004',
                'rfid_card_number' => 'CARD000010',
                'nama' => 'Lisa Andriani',
                'email' => 'lisa.andriani@company.com',
                'jabatan' => 'Marketing Staff',
                'departemen' => 'Marketing',
                'telepon' => '081234567010',
                'alamat' => 'Jl. Kebayoran Baru No. 50, Jakarta Selatan',
                'tanggal_masuk' => '2020-02-01',
                'status' => 'AKTIF',
                'gaji_pokok' => 7000000.00,
                'tunjangan_jabatan' => 1500000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR005',
                'rfid_card_number' => 'CARD000011',
                'nama' => 'Eko Prasetyo',
                'email' => 'eko.prasetyo@company.com',
                'jabatan' => 'System Administrator',
                'departemen' => 'Information Technology',
                'telepon' => '081234567011',
                'alamat' => 'Jl. Mampang Prapatan No. 35, Jakarta Selatan',
                'tanggal_masuk' => '2020-08-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 8500000.00,
                'tunjangan_jabatan' => 2200000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR006',
                'rfid_card_number' => 'CARD000012',
                'nama' => 'Fitri Handayani',
                'email' => 'fitri.handayani@company.com',
                'jabatan' => 'Customer Service',
                'departemen' => 'Customer Support',
                'telepon' => '081234567012',
                'alamat' => 'Jl. Pondok Indah No. 20, Jakarta Selatan',
                'tanggal_masuk' => '2021-01-10',
                'status' => 'AKTIF',
                'gaji_pokok' => 6500000.00,
                'tunjangan_jabatan' => 1200000.00,
                'tunjangan_transport' => 900000.00,
                'tunjangan_makan' => 700000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR007',
                'rfid_card_number' => 'CARD000013',
                'nama' => 'Hendra Gunawan',
                'email' => 'hendra.gunawan@company.com',
                'jabatan' => 'Data Analyst',
                'departemen' => 'Information Technology',
                'telepon' => '081234567013',
                'alamat' => 'Jl. Senopati No. 15, Jakarta Selatan',
                'tanggal_masuk' => '2021-06-01',
                'status' => 'AKTIF',
                'gaji_pokok' => 9000000.00,
                'tunjangan_jabatan' => 2500000.00,
                'tunjangan_transport' => 1200000.00,
                'tunjangan_makan' => 900000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR008',
                'rfid_card_number' => 'CARD000014',
                'nama' => 'Indah Permata',
                'email' => 'indah.permata@company.com',
                'jabatan' => 'Graphic Designer',
                'departemen' => 'Marketing',
                'telepon' => '081234567014',
                'alamat' => 'Jl. Pejaten Barat No. 40, Jakarta Selatan',
                'tanggal_masuk' => '2021-09-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 7500000.00,
                'tunjangan_jabatan' => 1800000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR009',
                'rfid_card_number' => 'CARD000015',
                'nama' => 'Joko Widodo',
                'email' => 'joko.widodo@company.com',
                'jabatan' => 'Quality Assurance',
                'departemen' => 'Information Technology',
                'telepon' => '081234567015',
                'alamat' => 'Jl. Cilandak No. 25, Jakarta Selatan',
                'tanggal_masuk' => '2022-02-01',
                'status' => 'AKTIF',
                'gaji_pokok' => 8000000.00,
                'tunjangan_jabatan' => 2000000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR010',
                'rfid_card_number' => 'CARD000016',
                'nama' => 'Kartika Sari',
                'email' => 'kartika.sari@company.com',
                'jabatan' => 'Content Writer',
                'departemen' => 'Marketing',
                'telepon' => '081234567016',
                'alamat' => 'Jl. Fatmawati No. 60, Jakarta Selatan',
                'tanggal_masuk' => '2022-05-20',
                'status' => 'AKTIF',
                'gaji_pokok' => 6800000.00,
                'tunjangan_jabatan' => 1500000.00,
                'tunjangan_transport' => 900000.00,
                'tunjangan_makan' => 700000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR011',
                'rfid_card_number' => 'CARD000017',
                'nama' => 'Lukman Hakim',
                'email' => 'lukman.hakim@company.com',
                'jabatan' => 'Network Engineer',
                'departemen' => 'Information Technology',
                'telepon' => '081234567017',
                'alamat' => 'Jl. Pasar Minggu No. 10, Jakarta Selatan',
                'tanggal_masuk' => '2022-09-01',
                'status' => 'AKTIF',
                'gaji_pokok' => 9500000.00,
                'tunjangan_jabatan' => 2800000.00,
                'tunjangan_transport' => 1200000.00,
                'tunjangan_makan' => 900000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR012',
                'rfid_card_number' => 'CARD000018',
                'nama' => 'Mega Putri',
                'email' => 'mega.putri@company.com',
                'jabatan' => 'Legal Staff',
                'departemen' => 'Legal',
                'telepon' => '081234567018',
                'alamat' => 'Jl. Kalibata No. 28, Jakarta Selatan',
                'tanggal_masuk' => '2023-01-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 8500000.00,
                'tunjangan_jabatan' => 2200000.00,
                'tunjangan_transport' => 1000000.00,
                'tunjangan_makan' => 800000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR013',
                'rfid_card_number' => 'CARD000019',
                'nama' => 'Nanda Pratama',
                'email' => 'nanda.pratama@company.com',
                'jabatan' => 'DevOps Engineer',
                'departemen' => 'Information Technology',
                'telepon' => '081234567019',
                'alamat' => 'Jl. Cipete Raya No. 33, Jakarta Selatan',
                'tanggal_masuk' => '2023-04-01',
                'status' => 'AKTIF',
                'gaji_pokok' => 11000000.00,
                'tunjangan_jabatan' => 3500000.00,
                'tunjangan_transport' => 1500000.00,
                'tunjangan_makan' => 1000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nip' => 'JNR014',
                'rfid_card_number' => 'CARD000020',
                'nama' => 'Olivia Tanjung',
                'email' => 'olivia.tanjung@company.com',
                'jabatan' => 'Business Analyst',
                'departemen' => 'Business Development',
                'telepon' => '081234567020',
                'alamat' => 'Jl. Bangka Raya No. 55, Jakarta Selatan',
                'tanggal_masuk' => '2023-07-15',
                'status' => 'AKTIF',
                'gaji_pokok' => 10000000.00,
                'tunjangan_jabatan' => 3000000.00,
                'tunjangan_transport' => 1300000.00,
                'tunjangan_makan' => 1000000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($karyawan as $data) {
            // Insert karyawan
            DB::table('karyawan')->insert($data);
            
            // Update status RFID card menjadi ASSIGNED
            if ($data['rfid_card_number']) {
                DB::table('available_rfid')
                    ->where('card_number', $data['rfid_card_number'])
                    ->update([
                        'karyawan_id' => $data['id'],
                        'status' => 'ASSIGNED',
                        'assigned_at' => now(),
                        'updated_at' => now(),
                    ]);
            }
        }
    }
}